=== dimplerohara/eloader/Microservices/filenet/cms-importmetadata-service/src/main/resources/xsd/objectType.xsd
<?xml version="1.0"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com) by Pankaj (HCL) -->
<xs:schema xmlns="urn:rm.bulk.hcl.neo.com:schema.objecttype.20141806" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:rm.bulk.hcl.neo.com:schema.objecttype.20141806">
	<xs:complexType name="PropertyInformation">
		<xs:sequence>
			<xs:element name="DefaultValues" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ValueAssist" type="ValueAssist" minOccurs="0"/>
			<xs:element name="ValueMap" type="ValueInformation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Dependencies" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="datatype" type="DataType" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="label" type="xs:string"/>
		<xs:attribute name="description" type="xs:string"/>
		<xs:attribute name="isArray" type="xs:boolean" use="required"/>
		<xs:attribute name="isSearchable" type="xs:boolean" use="required"/>
		<xs:attribute name="isDynamic" type="xs:boolean" use="required"/>
		<xs:attribute name="length" type="xs:int" use="required"/>
		<xs:attribute name="isNotNull" type="xs:boolean" use="required"/>
		<xs:attribute name="isRequired" type="xs:boolean" use="required"/>
		<xs:attribute name="isReadOnly" type="xs:boolean" use="required"/>
		<xs:attribute name="isHidden" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="ValueAssist">
		<xs:sequence>
			<xs:element name="Values" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="allowUserValues" type="xs:boolean" use="required"/>		
	</xs:complexType>
	<xs:complexType name="ValueInformation">
			<xs:sequence/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="label" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TypeInformation">
		<xs:sequence>
			<xs:element name="PropertyInformation" type="PropertyInformation" minOccurs="0" maxOccurs="unbounded">
				<xs:key name="pname">
					<xs:selector xpath="."/>
					<xs:field xpath="@name"/>
				</xs:key>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="label" type="xs:string"/>
		<xs:attribute name="description" type="xs:string"/>
		<xs:attribute name="parentName" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="DataType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="STRING"/>
			<xs:enumeration value="SHORT"/>
			<xs:enumeration value="INTEGER"/>
			<xs:enumeration value="LONG"/>
			<xs:enumeration value="DOUBLE"/>
			<xs:enumeration value="DATE"/>
			<xs:enumeration value="BOOLEAN"/>
			<xs:enumeration value="OBJECT_ID"/>
			<xs:enumeration value="CUSTOM"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="ObjectTypeSet" type="ObjectTypeSet"/>
	<xs:complexType name="ObjectTypeSet">
		<xs:sequence>
			<xs:element name="TypeInformation" type="TypeInformation" maxOccurs="unbounded">
				<xs:key name="type">
					<xs:selector xpath="."/>
					<xs:field xpath="@name"/>
				</xs:key>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== dimplerohara/eloader/Microservices/dctm-export-service/src/main/resources/xml/objectType.xml
<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<ObjectTypeSet xmlns="urn:rm.bulk.hcl.neo.com:schema.objecttype.20141806"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:rm.bulk.hcl.neo.com:schema.objecttype.20141806 file:///C:/Users/vsrivpa/Documents/NetBeansProjects/repository-mgr/src/main/resources/xsd/objectType.xsd">
	<TypeInformation description="DM Document" label="DM Document"
		name="dm_document" parentName="dm_sysobject">
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Name" length="255" name="object_name" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Title" length="400" name="title" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Subject" length="192" name="subject" />
		<PropertyInformation datatype="STRING"
			description="" isArray="true" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Authors" length="48" name="authors" />
		<PropertyInformation datatype="STRING"
			description="" isArray="true" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Keywords" length="48" name="keywords" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="false"
			label="Application Type" length="32" name="a_application_type" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="false"
			label="Status" length="16" name="a_status" />
		<PropertyInformation datatype="BOOLEAN"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Hidden" length="0" name="a_is_hidden" />
		<PropertyInformation datatype="DATE" description=""
			isArray="false" isDynamic="false" isHidden="false" isNotNull="false"
			isReadOnly="false" isRequired="false" isSearchable="false" label="Retained"
			length="0" name="a_retention_date" />
		<PropertyInformation datatype="BOOLEAN"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="false"
			label="Archive" length="0" name="a_archive" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="false"
			label="Compound Architecture" length="16" name="a_compound_architecture" />
		<PropertyInformation datatype="BOOLEAN"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Link Resolved" length="0" name="a_link_resolved" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="false"
			label="Resolution Version" length="32" name="resolution_label" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Format" length="32" name="a_content_type" />
		<PropertyInformation datatype="BOOLEAN"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Full Text Indexed" length="0" name="a_full_text" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="false"
			label="Storage Type" length="64" name="a_storage_type" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Owner Name" length="32" name="owner_name" />
		<PropertyInformation datatype="INTEGER"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Owner Permission" length="0" name="owner_permit">
			<ValueMap label="None" value="1" />
			<ValueMap label="Browse" value="2" />
			<ValueMap label="Read" value="3" />
			<ValueMap label="Relate" value="4" />
			<ValueMap label="Version" value="5" />
			<ValueMap label="Write" value="6" />
			<ValueMap label="Delete" value="7" />
		</PropertyInformation>
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Group Name" length="32" name="group_name" />
		<PropertyInformation datatype="INTEGER"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Group Permit" length="0" name="group_permit">
			<ValueMap label="None" value="1" />
			<ValueMap label="Browse" value="2" />
			<ValueMap label="Read" value="3" />
			<ValueMap label="Relate" value="4" />
			<ValueMap label="Version" value="5" />
			<ValueMap label="Write" value="6" />
			<ValueMap label="Delete" value="7" />
		</PropertyInformation>
		<PropertyInformation datatype="INTEGER"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="World Permissions" length="0" name="world_permit">
			<ValueMap label="None" value="1" />
			<ValueMap label="Browse" value="2" />
			<ValueMap label="Read" value="3" />
			<ValueMap label="Relate" value="4" />
			<ValueMap label="Version" value="5" />
			<ValueMap label="Write" value="6" />
			<ValueMap label="Delete" value="7" />
		</PropertyInformation>
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="User Comments" length="120" name="log_entry" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="false"
			label="ACL Domain" length="32" name="acl_domain" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="false"
			label="ACL Name" length="32" name="acl_name" />
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="false"
			label="Special Application" length="32" name="a_special_app" />
	</TypeInformation>
</ObjectTypeSet>

=== dimplerohara/eloader/Microservices/filenet/export-service/src/main/resources/xml/objectType.xml
<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<ObjectTypeSet xmlns="urn:rm.bulk.hcl.neo.com:schema.objecttype.20141806"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="urn:rm.bulk.hcl.neo.com:schema.objecttype.20141806 file:///C:/Users/vsrivpa/Documents/NetBeansProjects/repository-mgr/src/main/resources/xsd/objectType.xsd">	
	<TypeInformation description="CMS Document" label="CMS Document"
		name="DOCUMENT" parentName="IndependentObject">
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Owner" length="255" name="owner" />		
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="title" length="255" name="title" />	
		<PropertyInformation datatype="DATE"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Retention Date" length="255" name="retention date" />	
			
			
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Mime Type" length="255" name="mime type" />
		<PropertyInformation datatype="LONG"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Compound Document State" length="255" name="Compound Document State" />				
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Component Binding Label" length="255" name="Component Binding Label" />		
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Entry Template Object Store Name" length="255" name="Entry Template Object Store Name" />	
		<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Entry Template Launched Workflow Number" length="255" name="Entry Template Launched Workflow Number" />	
		
		
		
		
		<PropertyInformation datatype="BOOLEAN"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Inherit Parent Permission" length="255" name="Inherit Parent Permissions" />	
			<PropertyInformation datatype="BOOLEAN"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="IsHiddenContainer" length="255" name="IsHiddenContainer" />	
			<PropertyInformation datatype="STRING"
			description="" isArray="false" isDynamic="false" isHidden="false"
			isNotNull="false" isReadOnly="false" isRequired="false" isSearchable="true"
			label="Container Type" length="255" name="Container Type" />		
	</TypeInformation>
</ObjectTypeSet>
